<?php /** @var \Snowdog\DevTest\Controller\IndexAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cache Warmer</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">

    <?php if (isset($_SESSION['flash'])): ?>
        <p class="bg-info"><?= $_SESSION['flash'] ?></p>
        <?php unset($_SESSION['flash']) ?>
    <?php endif ?>

    <div>
        <h1>Cache Warmer</h1>
        <?php if ($this->user): ?>

            <form action="/sitemap-import" method="post"
                  enctype="multipart/form-data" class="form-inline form-group padded">
                <label for="sitemap">Select sitemap to upload</label>
                <input type="file" name="sitemap" id="sitemap" accept=".xml"><br>
                <input type="submit" name="submit" class="btn btn-primary" value="Submit">
            </form>


        <?php endif ?>
    </div>

</div><!-- /.container -->


</body>
</html>